# Generated by Django 5.2.8 on 2025-11-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_alter_products_image_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
